# Generated by Django 3.0.2 on 2020-02-03 14:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gdsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Category Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parents', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogs.gdsCategories')),
            ],
            options={
                'verbose_name': 'gdsCategory',
                'verbose_name_plural': 'gdsCategories',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Goods')),
                ('vendor_code', models.CharField(blank=True, max_length=32, verbose_name='Vendor Code')),
                ('unit', models.IntegerField(choices=[(1, 'thing'), (2, 'meter'), (3, 'packaging')], verbose_name='Unit')),
                ('description', models.TextField(blank=True, verbose_name='Deskription')),
                ('photo', models.ImageField(default='../static/images/nophoto.jpg', upload_to='goods/', verbose_name='Photo')),
                ('gdsCategories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogs.gdsCategories')),
            ],
        ),
    ]
