# Generated by Django 3.0.2 on 2020-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20200203_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
