# Generated by Django 3.0.2 on 2020-02-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('ico', models.CharField(max_length=16, verbose_name='Ico name')),
                ('url', models.URLField(verbose_name='URL Adress Social media')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled state')),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title work')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug Link')),
            ],
        ),
    ]
