# Generated by Django 3.0.2 on 2020-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='ico',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='title',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='type',
            field=models.IntegerField(choices=[(1, 'twitter'), (2, 'facebook'), (3, 'instagram'), (4, 'google-plus'), (5, 'linkedin'), (6, 'whatsapp'), (7, 'vk')], default=0, verbose_name='Social media'),
            preserve_default=False,
        ),
    ]
