# Generated by Django 3.0.2 on 2020-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200204_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social Net link', 'verbose_name_plural': 'Social Nets Links'},
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='type',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='socialtype',
            field=models.IntegerField(choices=[(0, '---'), (1, 'twitter'), (2, 'facebook'), (3, 'instagram'), (4, 'google-plus'), (5, 'linkedin'), (6, 'whatsapp'), (7, 'vk')], default=0, verbose_name='Social media'),
        ),
    ]
