# Generated by Django 3.0.2 on 2020-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200204_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['my_order'], 'verbose_name': 'Social Net link', 'verbose_name_plural': 'Social Nets Links'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
