# Generated by Django 3.0.2 on 2020-02-02 12:56

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=6768768, max_length=12, unique=True, validators=[person.models.validate_phone], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
