# Generated by Django 3.0.2 on 2020-02-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='storage name')),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Offices')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
    ]
